import { todoFilterList } from '../models/filter.model';
import { todoSortList } from '../models/sort.model';

export const sortOutput = {
    [`${todoSortList[0].key} ${todoSortList[0].order}`]: [
        {
            id: 1,
            title: 'Complete Angular project',
            deadline: [new Date('2025-10-05T00:00:00.000Z')],
            isCompleted: false,
            details: 'Finish the final module and deploy the project.',
        },
        {
            id: 10,
            title: 'Contribute to open-source project',
            deadline: [new Date('2025-03-30T00:00:00.000Z')],
            isCompleted: false,
            details: 'Find a good open-source project on GitHub and submit a pull request.',
        },
        {
            id: 2,
            title: 'Fix API authentication issue',
            deadline: [new Date('2025-03-08T00:00:00.000Z')],
            isCompleted: true,
            details: 'Debug and fix JWT authentication problems in backend.',
        },
        {
            id: 9,
            title: 'Learn AWS S3 integration',
            deadline: [new Date('2025-03-22T00:00:00.000Z')],
            isCompleted: false,
            details: 'Explore how to upload, store, and retrieve files from AWS S3.',
        },
        {
            id: 5,
            title: 'Prepare for frontend interview',
            deadline: [new Date('2025-03-20T00:00:00.000Z')],
            isCompleted: false,
            details: 'Revise key concepts in React, Angular, and JavaScript.',
        },
        {
            id: 6,
            title: "Read 'Clean Code' book",
            deadline: [new Date('2025-03-25T00:00:00.000Z')],
            isCompleted: false,
            details: "Read and summarize key lessons from 'Clean Code' by Robert C. Martin.",
        },
        {
            id: 8,
            title: 'Refactor old React project',
            deadline: [new Date('2025-03-18T00:00:00.000Z')],
            isCompleted: false,
            details: 'Improve code structure, remove unused dependencies, and optimize performance.',
        },
        {
            id: 7,
            title: 'Set up CI/CD pipeline',
            deadline: [new Date('2025-03-14T00:00:00.000Z')],
            isCompleted: true,
            details: 'Implement GitHub Actions for automatic testing and deployment.',
        },
        {
            id: 4,
            title: 'Update portfolio website',
            deadline: [new Date('2025-03-12T00:00:00.000Z')],
            isCompleted: false,
            details: 'Add recent projects and improve UI/UX design.',
        },
        {
            id: 3,
            title: 'Write blog post on React performance',
            deadline: [new Date('2025-03-15T00:00:00.000Z')],
            isCompleted: false,
            details: 'Research React optimization techniques and write an article.',
        },
    ],
    [`${todoSortList[1].key} ${todoSortList[1].order}`]: [
        {
            id: 3,
            title: 'Write blog post on React performance',
            deadline: [new Date('2025-03-15T00:00:00.000Z')],
            isCompleted: false,
            details: 'Research React optimization techniques and write an article.',
        },
        {
            id: 4,
            title: 'Update portfolio website',
            deadline: [new Date('2025-03-12T00:00:00.000Z')],
            isCompleted: false,
            details: 'Add recent projects and improve UI/UX design.',
        },
        {
            id: 7,
            title: 'Set up CI/CD pipeline',
            deadline: [new Date('2025-03-14T00:00:00.000Z')],
            isCompleted: true,
            details: 'Implement GitHub Actions for automatic testing and deployment.',
        },
        {
            id: 8,
            title: 'Refactor old React project',
            deadline: [new Date('2025-03-18T00:00:00.000Z')],
            isCompleted: false,
            details: 'Improve code structure, remove unused dependencies, and optimize performance.',
        },
        {
            id: 6,
            title: "Read 'Clean Code' book",
            deadline: [new Date('2025-03-25T00:00:00.000Z')],
            isCompleted: false,
            details: "Read and summarize key lessons from 'Clean Code' by Robert C. Martin.",
        },
        {
            id: 5,
            title: 'Prepare for frontend interview',
            deadline: [new Date('2025-03-20T00:00:00.000Z')],
            isCompleted: false,
            details: 'Revise key concepts in React, Angular, and JavaScript.',
        },
        {
            id: 9,
            title: 'Learn AWS S3 integration',
            deadline: [new Date('2025-03-22T00:00:00.000Z')],
            isCompleted: false,
            details: 'Explore how to upload, store, and retrieve files from AWS S3.',
        },
        {
            id: 2,
            title: 'Fix API authentication issue',
            deadline: [new Date('2025-03-08T00:00:00.000Z')],
            isCompleted: true,
            details: 'Debug and fix JWT authentication problems in backend.',
        },
        {
            id: 10,
            title: 'Contribute to open-source project',
            deadline: [new Date('2025-03-30T00:00:00.000Z')],
            isCompleted: false,
            details: 'Find a good open-source project on GitHub and submit a pull request.',
        },
        {
            id: 1,
            title: 'Complete Angular project',
            deadline: [new Date('2025-10-05T00:00:00.000Z')],
            isCompleted: false,
            details: 'Finish the final module and deploy the project.',
        },
    ],
    [`${todoSortList[2].key} ${todoSortList[2].order}`]: [
        {
            id: 2,
            title: 'Fix API authentication issue',
            deadline: [new Date('2025-03-08T00:00:00.000Z')],
            isCompleted: true,
            details: 'Debug and fix JWT authentication problems in backend.',
        },
        {
            id: 4,
            title: 'Update portfolio website',
            deadline: [new Date('2025-03-12T00:00:00.000Z')],
            isCompleted: false,
            details: 'Add recent projects and improve UI/UX design.',
        },
        {
            id: 7,
            title: 'Set up CI/CD pipeline',
            deadline: [new Date('2025-03-14T00:00:00.000Z')],
            isCompleted: true,
            details: 'Implement GitHub Actions for automatic testing and deployment.',
        },
        {
            id: 3,
            title: 'Write blog post on React performance',
            deadline: [new Date('2025-03-15T00:00:00.000Z')],
            isCompleted: false,
            details: 'Research React optimization techniques and write an article.',
        },
        {
            id: 8,
            title: 'Refactor old React project',
            deadline: [new Date('2025-03-18T00:00:00.000Z')],
            isCompleted: false,
            details: 'Improve code structure, remove unused dependencies, and optimize performance.',
        },
        {
            id: 5,
            title: 'Prepare for frontend interview',
            deadline: [new Date('2025-03-20T00:00:00.000Z')],
            isCompleted: false,
            details: 'Revise key concepts in React, Angular, and JavaScript.',
        },
        {
            id: 9,
            title: 'Learn AWS S3 integration',
            deadline: [new Date('2025-03-22T00:00:00.000Z')],
            isCompleted: false,
            details: 'Explore how to upload, store, and retrieve files from AWS S3.',
        },
        {
            id: 6,
            title: "Read 'Clean Code' book",
            deadline: [new Date('2025-03-25T00:00:00.000Z')],
            isCompleted: false,
            details: "Read and summarize key lessons from 'Clean Code' by Robert C. Martin.",
        },
        {
            id: 10,
            title: 'Contribute to open-source project',
            deadline: [new Date('2025-03-30T00:00:00.000Z')],
            isCompleted: false,
            details: 'Find a good open-source project on GitHub and submit a pull request.',
        },
        {
            id: 1,
            title: 'Complete Angular project',
            deadline: [new Date('2025-10-05T00:00:00.000Z')],
            isCompleted: false,
            details: 'Finish the final module and deploy the project.',
        },
    ],
    [`${todoSortList[3].key} ${todoSortList[3].order}`]: [
        {
            id: 1,
            title: 'Complete Angular project',
            deadline: [new Date('2025-10-05T00:00:00.000Z')],
            isCompleted: false,
            details: 'Finish the final module and deploy the project.',
        },
        {
            id: 10,
            title: 'Contribute to open-source project',
            deadline: [new Date('2025-03-30T00:00:00.000Z')],
            isCompleted: false,
            details: 'Find a good open-source project on GitHub and submit a pull request.',
        },
        {
            id: 6,
            title: "Read 'Clean Code' book",
            deadline: [new Date('2025-03-25T00:00:00.000Z')],
            isCompleted: false,
            details: "Read and summarize key lessons from 'Clean Code' by Robert C. Martin.",
        },
        {
            id: 9,
            title: 'Learn AWS S3 integration',
            deadline: [new Date('2025-03-22T00:00:00.000Z')],
            isCompleted: false,
            details: 'Explore how to upload, store, and retrieve files from AWS S3.',
        },
        {
            id: 5,
            title: 'Prepare for frontend interview',
            deadline: [new Date('2025-03-20T00:00:00.000Z')],
            isCompleted: false,
            details: 'Revise key concepts in React, Angular, and JavaScript.',
        },
        {
            id: 8,
            title: 'Refactor old React project',
            deadline: [new Date('2025-03-18T00:00:00.000Z')],
            isCompleted: false,
            details: 'Improve code structure, remove unused dependencies, and optimize performance.',
        },
        {
            id: 3,
            title: 'Write blog post on React performance',
            deadline: [new Date('2025-03-15T00:00:00.000Z')],
            isCompleted: false,
            details: 'Research React optimization techniques and write an article.',
        },
        {
            id: 7,
            title: 'Set up CI/CD pipeline',
            deadline: [new Date('2025-03-14T00:00:00.000Z')],
            isCompleted: true,
            details: 'Implement GitHub Actions for automatic testing and deployment.',
        },
        {
            id: 4,
            title: 'Update portfolio website',
            deadline: [new Date('2025-03-12T00:00:00.000Z')],
            isCompleted: false,
            details: 'Add recent projects and improve UI/UX design.',
        },
        {
            id: 2,
            title: 'Fix API authentication issue',
            deadline: [new Date('2025-03-08T00:00:00.000Z')],
            isCompleted: true,
            details: 'Debug and fix JWT authentication problems in backend.',
        },
    ],
};

export const filterOutput = {
    [`${todoFilterList[0].key} ${todoFilterList[0].value}`]: [
        {
            id: 1,
            title: 'Complete Angular project',
            deadline: [new Date('2025-10-05T00:00:00.000Z')],
            isCompleted: false,
            details: 'Finish the final module and deploy the project.',
        },
        {
            id: 10,
            title: 'Contribute to open-source project',
            deadline: [new Date('2025-03-30T00:00:00.000Z')],
            isCompleted: false,
            details: 'Find a good open-source project on GitHub and submit a pull request.',
        },
        {
            id: 9,
            title: 'Learn AWS S3 integration',
            deadline: [new Date('2025-03-22T00:00:00.000Z')],
            isCompleted: false,
            details: 'Explore how to upload, store, and retrieve files from AWS S3.',
        },
        {
            id: 5,
            title: 'Prepare for frontend interview',
            deadline: [new Date('2025-03-20T00:00:00.000Z')],
            isCompleted: false,
            details: 'Revise key concepts in React, Angular, and JavaScript.',
        },
        {
            id: 6,
            title: "Read 'Clean Code' book",
            deadline: [new Date('2025-03-25T00:00:00.000Z')],
            isCompleted: false,
            details: "Read and summarize key lessons from 'Clean Code' by Robert C. Martin.",
        },
        {
            id: 8,
            title: 'Refactor old React project',
            deadline: [new Date('2025-03-18T00:00:00.000Z')],
            isCompleted: false,
            details: 'Improve code structure, remove unused dependencies, and optimize performance.',
        },
        {
            id: 4,
            title: 'Update portfolio website',
            deadline: [new Date('2025-03-12T00:00:00.000Z')],
            isCompleted: false,
            details: 'Add recent projects and improve UI/UX design.',
        },
        {
            id: 3,
            title: 'Write blog post on React performance',
            deadline: [new Date('2025-03-15T00:00:00.000Z')],
            isCompleted: false,
            details: 'Research React optimization techniques and write an article.',
        },
    ],
    [`${todoFilterList[1].key} ${todoFilterList[1].value}`]: [
        {
            id: 2,
            title: 'Fix API authentication issue',
            deadline: [new Date('2025-03-08T00:00:00.000Z')],
            isCompleted: true,
            details: 'Debug and fix JWT authentication problems in backend.',
        },
        {
            id: 7,
            title: 'Set up CI/CD pipeline',
            deadline: [new Date('2025-03-14T00:00:00.000Z')],
            isCompleted: true,
            details: 'Implement GitHub Actions for automatic testing and deployment.',
        },
    ],
    [`${todoFilterList[2].key} ${todoFilterList[2].value}`]: [
        {
            id: 1,
            title: 'Complete Angular project',
            deadline: [new Date('2025-10-05T00:00:00.000Z')],
            isCompleted: false,
            details: 'Finish the final module and deploy the project.',
        },
        {
            id: 10,
            title: 'Contribute to open-source project',
            deadline: [new Date('2025-03-30T00:00:00.000Z')],
            isCompleted: false,
            details: 'Find a good open-source project on GitHub and submit a pull request.',
        },
        {
            id: 2,
            title: 'Fix API authentication issue',
            deadline: [new Date('2025-03-08T00:00:00.000Z')],
            isCompleted: true,
            details: 'Debug and fix JWT authentication problems in backend.',
        },
        {
            id: 9,
            title: 'Learn AWS S3 integration',
            deadline: [new Date('2025-03-22T00:00:00.000Z')],
            isCompleted: false,
            details: 'Explore how to upload, store, and retrieve files from AWS S3.',
        },
        {
            id: 5,
            title: 'Prepare for frontend interview',
            deadline: [new Date('2025-03-20T00:00:00.000Z')],
            isCompleted: false,
            details: 'Revise key concepts in React, Angular, and JavaScript.',
        },
        {
            id: 6,
            title: "Read 'Clean Code' book",
            deadline: [new Date('2025-03-25T00:00:00.000Z')],
            isCompleted: false,
            details: "Read and summarize key lessons from 'Clean Code' by Robert C. Martin.",
        },
        {
            id: 8,
            title: 'Refactor old React project',
            deadline: [new Date('2025-03-18T00:00:00.000Z')],
            isCompleted: false,
            details: 'Improve code structure, remove unused dependencies, and optimize performance.',
        },
        {
            id: 7,
            title: 'Set up CI/CD pipeline',
            deadline: [new Date('2025-03-14T00:00:00.000Z')],
            isCompleted: true,
            details: 'Implement GitHub Actions for automatic testing and deployment.',
        },
        {
            id: 4,
            title: 'Update portfolio website',
            deadline: [new Date('2025-03-12T00:00:00.000Z')],
            isCompleted: false,
            details: 'Add recent projects and improve UI/UX design.',
        },
        {
            id: 3,
            title: 'Write blog post on React performance',
            deadline: [new Date('2025-03-15T00:00:00.000Z')],
            isCompleted: false,
            details: 'Research React optimization techniques and write an article.',
        },
    ],
};
